### ISSUE TITLE
(just curious) Any real usage of this?

### ISSUE THREAD

**Issue by Naereen** [Ivoah/minimap#3]
I love this project. But I can't think of a situation where this could be useful (this is not a hard criticism, I am seriously wondering).
Any idea?

**Comment by Ivoah** [comment]
This is what I said to a similar comment on hackernews
> There really isn't much use for a tool like this. I mostly made it just to have fun with python and mess around with pygments. One possible use case could be for generating images for a website perhaps? It might be neat to have a minimap of the code of a website as its background.

**Comment by Naereen** [comment]
OK, that's actually interesting, thanks.

**Comment by Ivoah** [comment]
no problem
